# Sources of sequences to include in the ingest run
sources: ['genbank']

# Pathogen NCBI Taxonomy ID
ncbi_taxon_id: 'taxon 10244'
# Pathogen NCBI Accession Number
#accession: 'accession NC_063383.1'
# Pathogen NCBI Accession List
#accession_list: 'accession --inputfile config/accession_list.txt'
# Pathogen NCBI Geographic Region
#geo_location: '--geo-location USA'
# Pathogen NCBI Release Date
#release_date: '--released-after 01/01/2023'

# Renames the NCBI dataset headers
ncbi_field_map: 'config/ncbi-field-map.tsv'

# Params for the curate rule
curate:
  # Fields to rename
  field_map:
    collected: date
    submitted: date_submitted
    genbank_accession: accession
    submitting_organization: institution
  # Standardized strain name regex
  # Currently accepts any characters since clear standard
  strain_regex: '^.+$'
  # Back up strain name field if 'strain' doesn't match regex above
  strain_backup_fields: ['accession']
  # List of date fields to standardize
  date_fields: ['date', 'date_submitted']
  # Expected date formats by datetime for date fields
  # https://docs.python.org/3.9/library/datetime.html#strftime-and-strptime-format-codes
  expected_date_formats: ['%Y', '%Y-%m', '%Y-%m-%d', '%Y-%m-%dT%H:%M:%SZ', '%m/%d/%Y']
  # The expected field that contains the GenBank geo_loc_name
  genbank_location_field: location
  # Titlecase rules
  titlecase:
    # Abbreviations not cast to titlecase, keeps uppercase
    abbreviations: ['USA']
    # Articles that should not be cast to titlecase
    articles: [
      'and', 'd', 'de', 'del', 'des', 'di', 'do', 'en', 'l', 'la', 'las', 'le',
      'los', 'nad', 'of', 'op', 'sur', 'the', 'y'
    ]
    # List of string fields to titlecase
    fields: ['region', 'country', 'division', 'location']
  # Authors field name
  authors_field: 'authors'
  # Authors default value if authors value is empty
  authors_default_value: 'Unknown'
  # Field name for the generated abbreviated authors
  abbr_authors_field: 'abbr_authors'
  # General geolocation rules to apply to geolocation fields
  geolocation_rules_url: 'https://raw.githubusercontent.com/nextstrain/ncov-ingest/master/source-data/gisaid_geoLocationRules.tsv'
  # Local geolocation rules that overwrite the general geolocation rules provided above
  local_geolocation_rules: 'config/geolocation-rules.tsv'
  # User annotations file
  annotations: 'config/annotations.tsv'
  # ID field used to merge annotations
  annotations_id: 'accession'
  # Field to use as the sequence ID in the FASTA file
  id_field: 'accession'
  # Field to use as the sequence in the FASTA file
  sequence_field: 'sequence'
  # Final output columns for the metadata TSV
  metadata_columns: [
    'accession',
    'database',
    'strain',
    'note',
    'date',
    'date_year',
    'region',
    'country',
    'division',
    'location',
    'host',
    'date_submitted',
    'sra_accession',
    'abbr_authors',
    'authors',
    'institution',
    'length',
  ]

# Params for Nextclade related rules
nextclade:
  # Field to use as the sequence ID in the Nextclade file
  id_field: 'seqName'
  # Fields from a Nextclade file to be renamed (if desired) and appended to a metadata file
  field_map: 'config/nextclade-field-map.tsv'
